[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "isbn-lookup"
version = "0.0.1"
dependencies = [
    "httpx",
]

[project.scripts]
isbn-lookup = "isbn_lookup:main"
